- id: '1589536665369'
  alias: Open the window on power outage date
  description: ''
  trigger:
  - at: 08:12:00
    platform: time
  condition:
  - condition: state
    entity_id: sensor.date
    state: '2020-09-21'
  action:
  - data:
      position: 40
    entity_id: cover.bedroom_window1
    service: cover.set_cover_position
  mode: single
- id: '1589664836212'
  alias: turn AC on on power outage morning
  description: ''
  trigger:
  - at: 08:10:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.bedroom_ac_switch
    service: switch.turn_on
  - delay: 00:00:10
  - data:
      temperature: 21
    entity_id: climate.bedroom_aircondition
    service: climate.set_temperature
  mode: single
