homeassistant:
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml
  allowlist_external_urls:
    - "http://127.0.0.1:8123/api/media_player_proxy"
  auth_providers:
  - type: homeassistant

default_config:



color_extractor:

discovery:
  ignore:
    - yeelight

duckdns:
  domain: !secret duckdnsdomain
  access_token: !secret duckdnstoken

ffmpeg:

# Calendar
google:
  client_id: !secret googlecal_client
  client_secret: !secret googlecal_secret

history:
  exclude:
    domains:
      - script
      - group
      - calendar
      - automation
      - camera
    entities:
      - sensor.time
      - sensor.seattle_time

http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  ip_ban_enabled: True
  login_attempts_threshold: !secret login_attempts
  use_x_forwarded_for: True
  trusted_proxies:
    - !secret proxy1
    - !secret proxy2

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  database: !secret influx_db
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.bedroom_window_position
      - sensor.miband_battery
      - sensor.disconnected_minutes_today
    entity_globs:
      - sensor.printer_*
      - binary_sensor.ping_*

logbook:
  exclude:
    entities:
      - media_player.mibox3
      - media_player.mibox3_2

logger:
  default: warn
  logs:
    pychromecast.socket_client: fatal
  #   homeassistant.core: info

python_script:

recorder:
  db_url: !secret db_url
  # How many days to keep
  purge_keep_days: 3
  exclude:
    domains:
      - camera
    entities:
      - sensor.time
      - sensor.seattle_time

smartir:
  check_updates: false

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret

telegram_bot:
  - platform: polling
    parse_mode: html
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid1
      - !secret telegram_chatid2
      - !secret telegram_chatid3

tts:
  - platform: google_translate
    service_name: google_say

automation: !include automations.yaml
automation old: !include_dir_merge_list yaml/Automations/
binary_sensor: !include yaml/binarysensors.yaml
camera: !include yaml/cameras.yaml
climate: !include yaml/climates.yaml
frontend:
  themes: !include_dir_merge_named themes/
google_assistant: !include yaml/google_assistant.yaml
group: !include_dir_merge_named yaml/Groups/
input_text: !include yaml/inputtexts.yaml
lock: !include yaml/locks.yaml
media_player: !include yaml/mediaplayers.yaml
notify: !include yaml/notifys.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named yaml/Scripts/
sensor: !include_dir_merge_list yaml/Sensors/
switch: !include_dir_merge_list yaml/Switches/
template: !include yaml/templates.yaml
zone: !include yaml/zones.yaml