# Broadlink Switches
- platform: broadlink
  mac: !secret broadlink_mac
  switches:
    - name: "Bedroom Screen"
      command_on: !secret toshiba_ir_toggle
      command_off: !secret toshiba_ir_toggle