# Climate On/Off Switch
- platform: template
  switches:
    bedroom_ac_switch:
      friendly_name: "Bedroom AC"
      value_template: "{{not is_state('climate.bedroom_aircondition', 'off') }}"
      turn_off:
        service: climate.turn_off
        target:
          entity_id: climate.bedroom_aircondition
      turn_on:
        service: climate.turn_on
        target:
          entity_id: climate.bedroom_aircondition