- alias: When Fan ON AC OFF
  id: fan_on_ac_off
  trigger:
  - platform: state
    entity_id: fan.bedroom_fan
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.bedroom_ac_switch
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_ac_switch
    



- alias: When AC ON Fan OFF
  id: ac_on_fan_off
  trigger:
  - platform: state
    entity_id: switch.bedroom_ac_switch
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: fan.bedroom_fan
    state: 'on'
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.bedroom_fan
    



- alias: When AC ON cool Sweep ON
  id: ac_on_cool_sweep_on
  trigger:
  - platform: state
    entity_id: climate.bedroom_aircondition
    from: 'off'
    to: 'cool'
  action:
  - delay: 00:00:03
  - service: script.ac_sweep


- alias: When AC ON Announce Temperature
  id: ac_on_announcement
  trigger:
  - platform: state
    entity_id: switch.bedroom_ac_switch
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.ga_broadcast
    data:
      message: 'AC is set to {{ states.climate.bedroom_aircondition.state }}. Currently {{ states.climate.bedroom_aircondition.attributes.current_temperature }} degrees.'

- alias: When Fan ON Announce Temperature
  id: fan_on_announcement
  trigger:
  - platform: state
    entity_id: fan.bedroom_fan
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.ga_broadcast
    data:
      message: 'Fan speed is {{ states.fan.bedroom_fan.attributes.speed }}. Currently {{ states.climate.bedroom_aircondition.attributes.current_temperature }} degrees.'

- alias: AC Shutdown 20-Minutes Timer
  id: ac_sleep_timer
  mode: restart
  trigger:
  - platform: state
    entity_id: input_boolean.me_asleep
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      minutes: 20
  - condition: state
    entity_id: switch.bedroom_ac_switch
    state: 'on'
  - choose:
    # if heat: turn off and return
    - conditions:
        - condition: state
          entity_id: climate.bedroom_aircondition
          state: 'heat'
      sequence:
        - service: switch.turn_off
          target:
            entity_id: switch.bedroom_ac_switch
    # if not heat turn off and (maybe) turn fan on
    default:
      - service: switch.turn_off
        target:
          entity_id: switch.bedroom_ac_switch
      - condition: state
        entity_id: input_boolean.fan_on_after_falling_asleep_with_ac
        state: 'on'
      - delay:
          minutes: 10
      - condition: state
        entity_id: input_boolean.fan_on_after_falling_asleep_with_ac
        state: 'on'
      - service: fan.turn_on
        target:
          entity_id: fan.bedroom_fan
        data:
          percentage: 100

- alias: AC ON_OFF again
  id: ac_on_off_again
  mode: single
  trigger:
  - platform: state
    entity_id: switch.bedroom_ac_switch
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: switch.bedroom_ac_switch
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      seconds: 1
  - service: 'climate.turn_{{trigger.to_state.state}}'
    target:
      entity_id: climate.bedroom_aircondition
  - delay:
      seconds: 15