- alias: Turn Light on in Bedroom
  id: bedroom_light_on
  trigger:
  - platform: state
    entity_id: sensor.phone_home_wifi_connected
    to: Up
  - platform: numeric_state
    entity_id: sensor.sunlight_pct
    below: 11
  - platform: state
    entity_id: cover.bedroom_window1
    to: 'closed'
  condition:
  - condition: state
    entity_id: sensor.phone_home_wifi_connected
    state: Up
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.sunlight_pct
      below: 11
    - condition: state
      entity_id: cover.bedroom_window1
      state: 'closed'
  - condition: state
    entity_id: input_boolean.me_asleep
    state: 'off'
  - condition: state
    entity_id: light.bedroom_light
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 8
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.bedroom_light
          data:
            brightness: 255
            color_temp: 200
    default:
      - service: light.turn_on
        target:
          entity_id: light.bedroom_light
        data:
          brightness: 204
          color_temp: 312
  - service: notify.telegram_main
    data:
      title: "<b>Bedroom Light automatically turned ON</b>"
      message: >
        Triggered by: {{ trigger.platform }}
        {% if trigger.platform == 'state' %} {{ trigger.to_state.attributes.friendly_name }} {% endif %} #to4mi
      data:
        inline_keyboard:
          - 'Turn OFF:/turn_bedroom_light_off'


- alias: Undo turn on light
  id: bedroom_light_on_undo
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: turn_bedroom_light_off
  action:
  - service: light.turn_off
    target:
      entity_id: light.bedroom_light
  - service: notify.telegram_main
    data:
      message: "Bedroom Light turned OFF by request #to4mi"