- alias: Turn Light on in Bedroom
  trigger:
  - entity_id: sensor.phone_home_wifi_connected
    platform: state
    to: Up
  - platform: numeric_state
    entity_id: sensor.sunlight_pct
    below: 11
  - entity_id: cover.bedroom_window1
    platform: state
    to: 'closed'
  condition:
  - condition: state
    entity_id: sensor.phone_home_wifi_connected
    state: Up
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.sunlight_pct
      below: 11
    - condition: state
      entity_id: cover.bedroom_window1
      state: 'closed'
  - condition: state
    entity_id: input_boolean.asleep
    state: 'off'
  - condition: state
    entity_id: light.bedroom_light
    state: 'off'
  action:
  - data:
      brightness: 204
      entity_id: light.bedroom_light
      color_temp: 312
    service: light.turn_on
  - service: notify.telegram_main
    data_template:
      title: "<b>Bedroom Light automatically turned ON</b>"
      message: >
        Triggered by: {{ trigger.platform }}
        {% if trigger.platform == 'state' %} {{ trigger.to_state.attributes.friendly_name }} {% endif %} #to4mi
      data:
        inline_keyboard:
          - 'Turn OFF:/turn_bedroom_light_off'


- alias: Undo turn on light
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: turn_bedroom_light_off
  action:
  - data:
      entity_id:
      - light.bedroom_light
    service: light.turn_off
  - service: notify.telegram_main
    data:
      message: "Bedroom Light turned OFF by request #to4mi"