- alias: When Window Opens Mark Accordigly
  id: window_mark_open
  trigger:
  - platform: state
    entity_id: cover.bedroom_window1
    to: 'open'
    for:
      seconds: 2
  condition:
  - condition: state
    entity_id: input_boolean.window_improperly_closed
    state: 'off'
  - condition: not
    conditions:
      - condition: state
        entity_id: cover.bedroom_window1
        attribute: current_position
        state: 0
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.window_improperly_closed

- alias: Properly Close Window
  id: window_properly_close
  trigger:
  - platform: state
    entity_id: cover.bedroom_window1
    to: 'closed'
  condition:
  - condition: state
    entity_id: input_boolean.window_improperly_closed
    state: 'on'
  action:
  - delay:
      milliseconds: 500
  - service: cover.set_cover_position
    target:
      entity_id: cover.bedroom_window1
    data:
      position: 4
  - wait_template: "{{ is_state_attr('cover.bedroom_window1', 'current_position', 4) }}"
  - delay:
      milliseconds: 600
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.window_improperly_closed
  - service: cover.close_cover
    target:
      entity_id: cover.bedroom_window1

- alias: When Window Opens Sleep is Off
  id: window_open_sleep_off
  trigger:
  - platform: state
    entity_id: cover.bedroom_window1
    to: 'open'
  condition:
  - condition: state
    entity_id: input_boolean.me_asleep
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.me_asleep

- alias: Bedroom Window Position Getter
  id: bedroom_window_position_getter
  mode: restart
  trigger:
    - platform: state
      entity_id: cover.bedroom_window1
      to:
        - 'open'
        - 'closed'
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.bedroom_window_position
      data:
        value: '{{ trigger.to_state.attributes.current_position }}'

- alias: Bedroom Window Position Setter
  id: bedroom_window_position_setter
  mode: restart
  trigger:
    - platform: state
      entity_id: input_number.bedroom_window_position
  condition:
    - condition: numeric_state
      entity_id: input_number.bedroom_window_position
      below: 101
      above: -1
  action:
    - service: cover.set_cover_position
      target:
        entity_id: cover.bedroom_window1
      data:
        position: '{{ trigger.to_state.state | int }}'