- alias: Guest Mode On
  id: guest_on
  trigger:
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
  condition: []
  action:
  - service: automation.turn_off
    target:
      entity_id: group.bedroom_automations

- alias: Guest Mode Off
  id: guest_off
  trigger:
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
  condition: []
  action:
  - service: automation.turn_on
    target:
      entity_id: group.bedroom_automations

- alias: Guest Mode Telegram
  id: guest_telegram
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/guestmode"
  condition:
    - '{{ trigger.event.data["args"][0] == "on" or trigger.event.data["args"][0] == "off" }}'
  action:
  - service: telegram_bot.send_message
    data:
      target: '{{ trigger.event.data["chat_id"] }}'
      message: >
        {%- if states.input_boolean.guest_mode.state == trigger.event.data["args"][0] -%}
          Guest Mode was already {{ trigger.event.data["args"][0] }}
        {%- else -%}
          Guest Mode Turned {{ trigger.event.data["args"][0] | upper}}
        {%- endif -%}
  - service: 'input_boolean.turn_{{trigger.event.data["args"][0]}}'
    target:
      entity_id: input_boolean.guest_mode

- alias: Cleaning Guest Start
  id: cleaning_guest_on
  trigger:
  - platform: time
    at: input_datetime.house_cleaning_start
  condition: "{{(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] == states.input_select.houseclean_day.state)}}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.guest_mode

- alias: Cleaning Guest End
  id: cleaning_guest_off
  trigger:
  - platform: time
    at: input_datetime.house_cleaning_end
  condition: "{{(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] == states.input_select.houseclean_day.state)}}"
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.guest_mode