- alias: Turn everything off in Bedroom
  id: leaving_bedroom
  mode: single
  trigger:
  - platform: state
    entity_id: sensor.phone_home_wifi_connected
    from: "Up"
    to: "Down"
    for:
      minutes: 1
      seconds: 30
  - platform: state
    entity_id: sensor.phone_home_wifi_connected
    from:
      - "Up"
      - "Down"
    to: 'off'
    for:
      minutes: 3
  - platform: state
    entity_id: device_tracker.chen_nmap
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: script.offer_run_leaving_bedroom
    state: 'off'
  - condition: state
    entity_id: input_boolean.chen_asleep
    state: 'off'
  action:
  - service: notify.telegram_main
    data:
      title: "<b>You Have Left Your Bedroom</b>"
      message: >
        About to run leaving script.
        
        {% if trigger is defined -%} Triggered by: {{ trigger.to_state.attributes.friendly_name }} changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}
        {%- else -%}
        Triggered manually.
        {%- endif %} #to4mi
      data:
        inline_keyboard:
          - 'CANCEL:/cancel_leaving_bedroom'
  - service: script.offer_run_leaving_bedroom
  - delay:
      minutes: 15



- alias: Leaving Bedroom Cancel
  id: leaving_bedroom_cancel
  trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: cancel_leaving_bedroom
  action:
  - service: script.turn_off
    target:
      entity_id: script.offer_run_leaving_bedroom
  - service: notify.telegram_main
    data:
      title: "<b>I get it, you're in your room.</b>"
      message: "Canceled the leaving script. #to4mi"



- alias: Skip Bedroom Turn-off if Entering room
  id: leaving_bedroom_skip
  trigger:
  - platform: state
    entity_id: device_tracker.chen_nmap
    to: "home"
  - platform: state
    entity_id: sensor.phone_home_wifi_connected
    to: Up
  condition:
  - condition: state
    entity_id: script.offer_run_leaving_bedroom
    state: 'on'
  action:
  - service: automation.trigger
    target:
      entity_id: automation.leaving_bedroom_cancel
  - service: script.cancel_leaving_bedroom