- alias: Skype Turn On
  id: skype_on
  trigger: #Triggered at their 7am or when someone returns home
  - platform: state
    entity_id: group.familyathome
    to: home
  - platform: state
    entity_id: sensor.seattle_time
    to: "07:00"
  condition:
  - condition: state #Make sure we're home
    entity_id: group.familyathome
    state: home
  - condition: template #Make sure their time's correct
    value_template: '{{ states("sensor.seattle_time") >= "07:00" }}'
  - condition: time #Make sure our time is OK - not during the night - after midnight
    after: '11:00:00'
  - condition: state #Make sure it's not already on
    entity_id: switch.minix_down
    state: "off"
  - condition: or
    conditions:
      - condition: time #On their weekend
        weekday:
          - sat
          - sun
      - condition: state #Or their holiday
        entity_id: calendar.holidays_usa
        state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.minix_down
  - service: notify.telegram_main
    data:
      message: "Minix Down was automatically turned ON"

- alias: Skype Turn Off
  id: skype_off
  trigger:
  - platform: time
    at: '03:00:00'
  condition:
  - condition: state
    entity_id: switch.minix_down
    state: "on"
  - condition: state
    entity_id: media_player.livingroom_tv
    state: "off"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.minix_down
  - service: notify.telegram_main
    data:
      message: "Attempting to turn Minix Down OFF"