- alias: tasker receiver volume
  id: tasker_receiver_volume
  initial_state: True
  mode: queued
  trigger:
    platform: webhook
    webhook_id: !secret webhook_volume
  condition:
  - "{{ trigger.json.category == 'changevol' }}"
  - "{{ trigger.json.vol in ['up', 'down', 'mute'] }}"
  - condition: state
    entity_id: media_player.bedroom_receiver
    state: 'on'
  action:
  - service: 'media_player.volume_{{trigger.json.vol}}'
    target:
      entity_id: media_player.bedroom_receiver
  - delay:
      milliseconds: 100
  - service: 'media_player.volume_{{trigger.json.vol}}'
    target:
      entity_id: media_player.bedroom_receiver