- alias: Telegram To Automation
  id: telegram_to_automation
  trigger:
    - platform: event
      event_type: telegram_callback
  condition: []
  action:
  - service: automation.trigger
    data_template:
      entity_id: >
        {% if trigger.event.data.data == "/turn_bedroom_light_off" %}
          automation.undo_turn_on_light
        {% elif trigger.event.data.data == "/cancel_leaving_bedroom" %}
          automation.leaving_bedroom_cancel
        {% else %}
          automation.do_nothing
        {% endif %}
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'Feedback Received!'
      show_alert: false
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []