- alias: Warning Processor
  id: warning_processor
  mode: single
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_use
    above: '28'
    for:
      minutes: 5
  condition: []
  action:
  - service: notify.telegram_warnings
    data:
      title: "<b>Warning</b>"
      message: "High CPU Usage"
  - delay:
      minutes: 7


- alias: Warning Temperature
  id: warning_temperature
  mode: single
  trigger:
  - platform: numeric_state
    entity_id: sensor.cpu_temperature
    above: '72'
    for:
      minutes: 2
  condition: []
  action:
  - service: notify.telegram_warnings
    data:
      title: "<b>Warning</b>"
      message: "High CPU Temperature HASS #to4mi"
  - delay:
      minutes: 5

# Not in WARNINGS channel
- alias: Warning New Device
  id: warning_new_device
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
  - service: notify.telegram_main
    data:
      title: "<b>New Device</b>"
      message: >
          New device:
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})

# Not in WARNINGS channel
- alias: 'Update Available Notifications'
  id: hass_update_available
  trigger:
    - platform: state
      entity_id: sensor.version_latest
    # - platform: homeassistant
    #   event: start
  condition:
    - "{{ states('sensor.version_latest') != 'unknown'}}"
    - "{{ states('sensor.version_latest') > states('sensor.version_installed') }}"
  action:
  - service: telegram_bot.send_message
    data:
      target: !secret telegram_chatid1
      message: >
        Update [available](https://www.home-assistant.io/latest-release-notes/) for Hassio: {{states.sensor.version_latest.state}}
        {%- if states("sensor.version_latest")[-1]!="0" %}
        
        [GitHub Releases](https://github.com/home-assistant/core/releases){% endif %}
      disable_web_page_preview: true
      parse_mode: markdown


- alias: Warning Failed Login
  id: warning_failed_login
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
  condition:
    - "{{ trigger.to_state.state != off }}"
    - "{{ trigger.to_state.state != 'None' }}"
  action:
    - service: notify.telegram_warnings
      data:
        title: "Failed Hass Login Attempt #to4mi"
        message: "IP: {{ state_attr('persistent_notification.http_login', 'message').split('from')[1] }}"

- alias: Warning Snapshot Failure
  id: warning_snapshot
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.snapshots_stale
      to: 'on'
  condition: []
  action:
    - service: notify.telegram_warnings
      data:
        message: "Hassio Snapshots Stale #to4mi"

- alias: HACS Update Available
  id: hacs_persistent_notification
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.hacs
  condition:
    - "{{ states(trigger.entity_id) != 'unknown'}}"
  action:
    - choose:
        - conditions: "{{ (states(trigger.entity_id) | float) == 0}}"
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: hacsupdates
      default:
        - delay:
            minutes: 4
        - condition: template
          value_template: "{{ (states(trigger.entity_id) | float) != 0}}"
        - condition: template
          value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
        - service: persistent_notification.create
          data:
            title: Updates pending in HACS
            message: >-
              {% for repo in state_attr(trigger.entity_id, 'repositories') %}
                **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
              {% endfor %}
            notification_id: hacsupdates

- alias: Shelly Firmware Update Available
  id: shelly_fw_persistent_notification
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_2_5_firmware_update
      to: 'on'
  condition: []
  action:
    - service: persistent_notification.create
      data:
        title: Shelly Firmware Update Available
        message: "[Go to Settings]({{'http://' + states('sensor.shelly_2_5_ip')}})"
        notification_id: shellyfw

- alias: Warning Ink Replace Needed
  id: warning_ink
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.printer_black_ink_remaining
        - sensor.printer_cyan_ink_remaining
        - sensor.printer_magenta_ink_remaining
        - sensor.printer_yellow_ink_remaining
      below: 1
  condition: []
  action:
    - service: persistent_notification.create
      data:
        title: Ink needs to be replaced
        message: "Empty Cartridge: {{trigger.to_state.name.split(' ')[1]}}"
        notification_id: inkbrother
    - service: notify.telegram_warnings
      data:
        title: "🖨 Ink needs to be replaced. #to4mi"
        message: "Cartridge: {{trigger.to_state.name.split(' ')[1]}}"

# Locations Channel
- id: warning_lightning
  alias: Warning Close Storm
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.blitzortung_lightning_distance
      below: 17
      above: 2
  action:
  - service: notify.telegram_locations
    data:
      message: "does not show"
      data:
        location:
          latitude: '{{ trigger.to_state.attributes.lat }}'
          longitude: '{{ trigger.to_state.attributes.lon }}'
  - service: notify.telegram_locations
    data:
      title: "🌩 <b>Lightning Strike - {{trigger.to_state.state|round(0)}} km</b>"
      message: "Direction: {{states('sensor.blitzortung_lightning_azimuth')}}°"
  - delay:
      minutes: 25

# Locations Channel
- id: warning_lightning_2km
  alias: Warning Very Close Lightning
  mode: parallel
  trigger:
    - platform: numeric_state
      entity_id: sensor.blitzortung_lightning_distance
      below: 2.01
  action:
  - service: notify.telegram_locations
    data:
      message: "does not show"
      data:
        location:
          latitude: '{{ trigger.to_state.attributes.lat }}'
          longitude: '{{ trigger.to_state.attributes.lon }}'
  - service: notify.telegram_locations
    data:
      title: "🌩 <b>Very Close Lightning Strike - {{trigger.to_state.state|round(0)}} km</b>"
      message: "Direction: {{states('sensor.blitzortung_lightning_azimuth')}}°"