- platform: mqtt
  name: "My Computer - Connected"
  state_topic: "iotlink/workgroup/pc/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1

- platform: rpi_power