- platform: mqtt  
  name: "Bedroom Fan"
  command_topic: "cmnd/iFan03-2/FanSpeed"
  speed_command_topic: "cmnd/iFan03-2/FanSpeed"    
  state_topic: "stat/iFan03-2/RESULT"
  speed_state_topic: "stat/iFan03-2/RESULT"
  state_value_template: >
    {% if value_json.FanSpeed is defined %}
      {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}ON{%- endif %}
    {% else %}
      {% if states.fan.bedroom_fan.state == 'off' -%}0{%- elif states.fan.bedroom_fan.state == 'on' -%}ON{%- endif %}
    {% endif %}
  speed_value_template: "{{ value_json.FanSpeed }}"
  availability_topic: tele/iFan03-2/LWT
  payload_off: "0"
  payload_on: "ON"
  payload_low_speed: "1"
  payload_medium_speed: "2"
  payload_high_speed: "3"
  payload_available: Online
  payload_not_available: Offline
  qos: 1
  retain: true
  speeds:
    - "off"
    - low
    - medium
    - high