- platform: mqtt
  name: Computer Lock
  state_topic: "bedroom/computer/lock/state"
  command_topic: "bedroom/computer/lock/set"
  payload_lock: "lock"
  payload_unlock: "unlock"
  qos: 0

- platform: template
  name: My Computer Lock
  value_template: "{{ is_state('lock.computer_lock', 'locked') }}"
  lock:
    service: lock.lock
    data:
      entity_id: lock.computer_lock
  unlock:
    service: lock.unlock
    data:
      entity_id: lock.computer_lock
  availability_template: "{{ is_state('switch.my_computer', 'on') }}"