- platform: smartir
  name: Bedroom Receiver
  unique_id: bedroom_receiver
  device_code: 9521
  controller_data: !secret broadlink_ip

- platform: smartir
  name: Bedroom Mi Box
  unique_id: bedroom_mi_box
  device_code: 9520
  controller_data: !secret broadlink_ip