# CPU Temperature
- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '째C'
  value_template: '{{ value | multiply(0.001) | round(1) }}'

#  Statistics of RaspPi
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

# Versions for Update Notifications
- platform: version
  name: Version Installed
  source: local  
  
- platform: version
  name: Version Latest
  beta: false
  image: raspberrypi4-64
  source: hassio

# Router Temperature
- platform: command_line
  name: Asuswrt CPU Temp
  command: "ssh -p 22 -o StrictHostKeyChecking=no -i /config/.asus_ssh.key user@router.asus.com cat /sys/class/thermal/thermal_zone0/temp"
  scan_interval: 300
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: Asuswrt 2.4 GHz Temp
  command: "ssh -p 22 -o StrictHostKeyChecking=no -i /config/.asus_ssh.key user@router.asus.com wl -i eth5 phy_tempsense"
  scan_interval: 900
  unit_of_measurement: "째C"
  value_template: "{{ value.split(' ')[0] | multiply(0.5) + 20 }}"

- platform: command_line
  name: Asuswrt 5 GHz Temp
  command: "ssh -p 22 -o StrictHostKeyChecking=no -i /config/.asus_ssh.key user@router.asus.com wl -i eth6 phy_tempsense"
  scan_interval: 900
  unit_of_measurement: "째C"
  value_template: "{{ value.split(' ')[0] | multiply(0.5) + 20 }}"