- platform: template
  sensors:
    sunlight_pct:
      value_template: >-
        {%- set elevation = state_attr('sun.sun','elevation') | float %}
        {%- set cloud_coverage = states('sensor.dark_sky_cloud_coverage') | float %}
        {%- set cloud_factor = (1 - (0.75 * ( cloud_coverage / 100) ** 3 )) %}
        {%- set min_elevation = -6 %}
        {%- set max_elevation = 90 %}
        {%- set adjusted_elevation = elevation - min_elevation %}
        {%- set adjusted_elevation = [adjusted_elevation,0] | max %}
        {%- set adjusted_elevation = [adjusted_elevation,max_elevation - min_elevation] | min %}
        {%- set adjusted_elevation = adjusted_elevation / (max_elevation - min_elevation) %}
        {%- set adjusted_elevation = adjusted_elevation %}
        {%- set adjusted_elevation = adjusted_elevation * 100 %}
        {%- set brightness = adjusted_elevation * cloud_factor %}
        {{ brightness | round }}
      unit_of_measurement: '%'
      device_class: 'illuminance'
      unique_id: 'sunlight_calculation'
    bedroom_window_position:
      friendly_name: Bedroom Window Position
      value_template: "{{ state_attr('cover.bedroom_window1', 'current_position') }}"
      unique_id: 'bedroom_window_position'
      unit_of_measurement: '%'
    phone_home_wifi_connected:
      friendly_name: Phone Home WiFi Connected
      unique_id: 'phone_home_wifi_connected'
      value_template: >-
        {%- if states('sensor.phone_wifi_bssid')[:-2] in states('input_text.upssid') -%}
          Up
        {%- elif states('sensor.phone_wifi_bssid')[:-2] in states('input_text.downssid') -%}
          Down
        {%- elif states('sensor.phone_wifi_bssid')|length == 17 -%}
          {{ states('sensor.phone_wifi_bssid') }}
        {%- else -%}
          off
        {%- endif %}
      icon_template: >-
        {%- if states('sensor.phone_wifi_bssid')[:-2] in states('input_text.upssid') -%}
          mdi:transfer-up
        {%- elif states('sensor.phone_wifi_bssid')[:-2] in states('input_text.downssid') -%}
          mdi:transfer-down
        {%- elif states('sensor.phone_wifi_bssid')|length == 17 -%}
          mdi:cellphone-nfc
        {%- else -%}
          mdi:cellphone-nfc-off
        {%- endif %}