- platform: dht
  sensor: AM2302
  pin: D4
  monitored_conditions:
    - temperature
    - humidity

- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
#    - icon
    - precip_type
    - precip_intensity
    - precip_probability
#    - precip_accumulation
    - temperature
    - apparent_temperature
#    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
#    - pressure
    - visibility
#    - ozone
#    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
#    - moon_phase
#    - sunrise_time
#    - sunset_time
    - nearest_storm_distance
#    - nearest_storm_bearing
    - alerts
  scan_interval:
    minutes: 5
  units: ca